- url: https://exchange.xforce.ibmcloud.com/rss/collection?tag=advisory
  category: Crypto & Blockchain Security
  title: X-Force Exchange - Collection Feed
  type: rss
  description: Collections with tag "advisory"
  discovery:
    discovered_at: '2026-05-04T09:27:02.553158Z'
    score: 40
    matched_keywords:
    - apt
    - backdoor
    - c2
    - campaign
    - cve
    - denial of service
    - exploit
    - ioc
    - malware
    - patch
    - phishing
    - privilege escalation
    - ransomware
    - rce
    - security research
    - technique
    - threat actor
    - vuln
    - vulnerability
    discovered_via: rel=alternate
    url_hash: ba435beb2531b40628ac91572852d1323646b088
