- url: https://aboutdfir.com/feed/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-03-02T07:41:38.277786Z'
    score: 36
    matched_keywords:
    - authentication
    - aws
    - bypass
    - cve
    - dfir
    - exploit
    - lateral movement
    - malware
    - patch
    - persistence
    - ransomware
    - rce
    - threat actor
    - vuln
    - vulnerability
    - zero-day
    discovered_via: rel=alternate
    url_hash: cd09274df904f1b693916c560c6aac746ed4c1e4
- url: https://aboutdfir.com/rss/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-03-02T07:41:36.420152Z'
    score: 36
    matched_keywords:
    - authentication
    - aws
    - bypass
    - cve
    - dfir
    - exploit
    - lateral movement
    - malware
    - patch
    - persistence
    - ransomware
    - rce
    - threat actor
    - vuln
    - vulnerability
    - zero-day
    discovered_via: common_path
    url_hash: 714112b4ad6fe8f3c16147f089119749a1063796
